spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    password: 11
    url: "jdbc:postgresql://localhost:5432/sandbox"
    username: root
  mustache:
    servlet:
      expose-request-attributes:
  data:
    redis:
      host: localhost
      port: 6379

minio:
  host: localhost
  server:
    port: 9001
  console:
    port: 9002
  user: miniouser
  password: miniopass
