services:
  db:
    image: postgres
    container_name: sandbox_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=11
      - POSTGRES_DB=sandbox
    command: postgres -p 5432
    ports:
      - 5432:5432

  minio:
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    container_name: ${MINIO_HOST}
    image: quay.io/minio/minio
    ports:
      - ${MINIO_SERVER_PORT}:${MINIO_SERVER_PORT}
      - ${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}
    command: server --address :"${MINIO_SERVER_PORT}" --console-address :"${MINIO_CONSOLE_PORT}" /data
    volumes:
      - ./storage:/data
    restart: always
